#!/system/bin/sh
### CleanTWEAKS!

### CPU and VM Tweaks
echo 6144 > /sys/devices/virtual/bdi/179:48/read_ahead_kb
/system/xbin/sysctl -w fs.file-max=131072
/system/xbin/sysctl -w fs.inotify.max_queued_events=32768
/system/xbin/sysctl -w fs.inotify.max_user_instances=256
/system/xbin/sysctl -w fs.inotify.max_user_watches=10240
/system/xbin/sysctl -w fs.lease-break-time=10
/system/xbin/sysctl -w kernel.threads-max=524288
/system/xbin/sysctl -w net.ipv4.tcp_congestion_control=westwood
/system/xbin/sysctl -w net.ipv4.tcp_mem="4000000 4054304 4194304"
/system/xbin/sysctl -w net.ipv4.udp_mem="4000000 4054304 4194304"
/system/xbin/sysctl -w net.core.somaxconn=65536
/system/xbin/sysctl -w net.core.optmem_max=2097152
/system/xbin/sysctl -w net.core.rmem_max=4194304
/system/xbin/sysctl -w net.core.rmem_min=8192
/system/xbin/sysctl -w net.core.rmem_default=131072
/system/xbin/sysctl -w net.core.wmem_max=2097152
/system/xbin/sysctl -w net.core.wmem_min=4096
/system/xbin/sysctl -w net.core.wmem_default=65536
/system/xbin/sysctl -w net.ipv4.tcp_rmem_min=8192
/system/xbin/sysctl -w net.ipv4.tcp_rmem_default=131072
/system/xbin/sysctl -w net.ipv4.tcp_rmem="8192 131072 4194304"
/system/xbin/sysctl -w net.ipv4.tcp_wmem_min=4096
/system/xbin/sysctl -w net.ipv4.tcp_wmem_default=65536
/system/xbin/sysctl -w net.ipv4.tcp_wmem="4096 65536 2097152"
/system/xbin/sysctl -w net.ipv4.udp_rmem_min=8192
/system/xbin/sysctl -w net.ipv4.udp_rmem_default=131072
/system/xbin/sysctl -w net.ipv4.udp_rmem="8192 131072 4194304"
/system/xbin/sysctl -w net.ipv4.udp_wmem_min=4096
/system/xbin/sysctl -w net.ipv4.udp_wmem_default=65536
/system/xbin/sysctl -w net.ipv4.udp_wmem="4096 65536 2097152"
/system/xbin/sysctl -w net.ipv4.tcp_tw_reuse=1
/system/xbin/sysctl -w net.ipv4.tcp_tw_recycle=1
/system/xbin/sysctl -w net.ipv4.route.flush=1
/system/xbin/sysctl -w net.ipv6.route.flush=1

### Hotplug interfaced configuration
echo "0 0 0" > /sys/kernel/rt_config/rt_config

### GPU Under Volt!
echo "1400 1340 1275 1185 1130 1080 1035 975 920 855 800" > /sys/devices/system/cpu/cpu0/cpufreq/gpu_voltage_control

### CPU Under Volt!
echo "1370 1280 1220 1155 1090 980 910 860 825 750 720 680 630 610 560 490 340 270 215 185 150 130 85 60 45 40 35 30" > /sys/devices/system/cpu/cpu0/cpufreq/UV_mV_table

### Scheduler Setting
# Internal SD Card
#echo cfq > /sys/block/mmcblk0/queue/scheduler

# External SD Card
#echo cfq > /sys/block/mmcblk1/queue/scheduler

### Disable FSync
echo 0 > /sys/devices/virtual/misc/fsynccontrol/fsync_enabled