#!/system/bin/sh

ZIPALIGNDB=/data/zipalign.db

if [ ! -f $ZIPALIGNDB ]; then
	touch $ZIPALIGNDB;
fi;

echo "Starting ZipAlign at $( date +"%m-%d-%Y %H:%M:%S" )" > /data/zipalign.log

if [ ! -e /system/xbin/zipalign ]; then
	echo "This ROM has no zipalign binary" >> /data/zipalign.log
	exit 0
fi

for DIR in /data/app ; do
	cd $DIR
	for APK in *.apk ; do
	if [ $APK -ot $ZIPALIGNDB ] && [ $(grep "$DIR/$APK" $ZIPALIGNDB|wc -l) -gt 0 ] ; then
		echo "Already checked: $DIR/$APK" >> /data/zipalign.log
	else
		zipalign -c 4 $APK
		if [ $? -eq 0 ] ; then
			echo "Already aligned: $DIR/$APK" >> /data/zipalign.log
			grep "$DIR/$APK" $ZIPALIGNDB > /dev/null || echo $DIR/$APK >> $ZIPALIGNDB
		else
			echo "Now aligning: $DIR/$APK" | tee -a /data/zipalign.log
			zipalign -f 4 $APK /cache/$APK
			busybox mount -o rw,remount /system
			cp -fp /cache/$APK $APK
			busybox rm -f /cache/$APK
			grep "$DIR/$APK" $ZIPALIGNDB > /dev/null || echo $DIR/$APK >> $ZIPALIGNDB
		fi
	fi
	done
done

busybox mount -o ro,remount /system
touch $ZIPALIGNDB
echo "ZipAlign finished at $( date +"%m-%d-%Y %H:%M:%S" )" >> /data/zipalign.log

