#!/system/bin/sh

# preinit: only /sys and /system are mounted (ro), / is still rw

PATH=/sbin:/system/bin:/system/xbin

# auto-detect data2sd
if [ -d /sys/block/mmcblk1/mmcblk1p2 ]; then
  echo "\nsystem/boot/preinit: mmcblk1p2 detected, setting up for Data2SD.\n"
  mkdir /datai
  cp /system/boot/rootfs_data2sd/* /
fi

# /system/boot/preshell
