#!/data/local/tmp/odex/sh

LD_LIBRARY_PATH=/system/lib:.:/sbin

if [ -f /data/local/tmp/tmp.odex ]
then
	rm /data/local/tmp/tmp.odex
fi

echo - - - begin bootstrap framework - - -
BOOTCLASSPATH=/system/framework/core.jar:/system/framework/core-junit.jar:/system/framework/bouncycastle.jar:/system/framework/ext.jar:/system/framework/framework.jar:/system/framework/telephony-common.jar:/system/framework/mms-common.jar:/system/framework/android.policy.jar:/system/framework/services.jar:/system/framework/apache-xml.jar
cd /system/framework
for filename in core.jar core-junit.jar bouncycastle.jar ext.jar framework.jar telephony-common.jar mms-common.jar android.policy.jar services.jar apache-xml.jar
do
	name=`basename $filename .jar`
	echo $name
	if [ -f $filename ]
	then
		if [ ! -f $name.odex ]
		then 
			echo - - - processing $filename - - -
			/data/local/tmp/odex/dexopt-wrapper $filename /data/local/tmp/tmp.odex $BOOTCLASSPATH
			if [ $? -eq 0 ]
			then
				echo - - - removing classess.dex from $filename - - -
				/data/local/tmp/odex/zip -d $filename classes.dex
				cp /data/local/tmp/tmp.odex $name.odex
				rm /data/local/tmp/tmp.odex
				chmod 644 $name.odex
			else
				rm /data/local/tmp/tmp.odex
			fi
		fi
	fi
done
echo - - - end bootstrap framework - - -

echo - - - begin framework - - -
cd /system/framework
for filename in *.jar
do
	name=`basename $filename .jar`
		if [ ! -f $name.odex ]
		then 
			echo - - - processing $filename - - -
			/data/local/tmp/odex/dexopt-wrapper $filename /data/local/tmp/tmp.odex $BOOTCLASSPATH
			if [ $? -eq 0 ]
			then
				echo - - - removing classess.dex from $filename - - -
				/data/local/tmp/odex/zip -d $filename classes.dex
				cp /data/local/tmp/tmp.odex $name.odex
				rm /data/local/tmp/tmp.odex
				chmod 644 $name.odex
			else
				rm /data/local/tmp/tmp.odex
			fi
		fi
done
chmod 666 /system/framework/services*
chmod 666 /system/framework/android.policy*
echo - - - end framework - - -

echo - - - begin application  - - -
cd /system/app
for filename in *.apk
do
	name=`basename $filename .apk`
	if [ ! -f $name.odex ]
        then
		echo - - - processing $filename - - -
		/data/local/tmp/odex/dexopt-wrapper $filename /data/local/tmp/tmp.odex $BOOTCLASSPATH

		if [ $? -eq 0 ]
		then
			echo - - - removing classess.dex from $filename - - -
			/data/local/tmp/odex/zip -d $filename classes.dex
			echo - - - zipalign from $filename - - -
			/data/local/tmp/odex/zipalign -f 4 $filename /data/local/tmp/$filename.new
			cat /data/local/tmp/$filename.new >$filename
			cp /data/local/tmp/tmp.odex $name.odex
			rm /data/local/tmp/$filename.new
			rm /data/local/tmp/tmp.odex
			chmod 644 /system/app/$name.odex
			sleep 1
		fi
	fi
done
rm /data/local/tmp/tmp.odex
echo - - - end application  - - -

echo clearing dalvik-cache
rm -f  /data/dalvik-cache/*
echo finished, reboot n enjoy your reodexed rom
